name: Build Check

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Install Android SDK
        uses: android-actions/setup-android-sdk@v2
        with:
          sdk-platform: 'platforms;android-30'
          sdk-platform-tools: true

      - name: Install emulator dependencies
        run: sdkmanager --install "system-images;android-30;google_apis;x86"

      - name: Create emulator
        run: echo no | avdmanager create avd -n emulator -k "system-images;android-30;google_apis;x86" --device "Nexus 5X"

      - name: Start emulator
        run: $ANDROID_HOME/emulator/emulator -avd emulator -no-audio -no-window -accel auto -wipe-data &

      - name: Wait for emulator to start
        run: android-wait-for-emulator

      - name: Run tests
        run: ./gradlew connectedCheck
